name: Build binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build
        uses: wttw/actions/golang-build@master
        env:
          COMPRESS_FILES: 1
        with:
          args: linux/amd64 darwin/amd64 windows/amd64

      - name: Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
              - Is new
          draft: false
          prerelease: false

      - name: Upload Linux
        id: upload-release-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .release/wordpress-export_linux_amd64.zip
          asset_name: wordpress-export_linux_amd64.zip
          asset_content_type: application/zip

      - name: Upload Windows
        id: upload-release-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .release/wordpress-export_windows_amd64.zip
          asset_name: wordpress-export_windows_amd64.zip
          asset_content_type: application/zip

      - name: Upload Mac
        id: upload-release-mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .release/wordpress-export_darwin_amd64.zip
          asset_name: wordpress-export_darwin_amd64.zip
          asset_content_type: application/zip

